### ISSUE TITLE
Litter ??? Help

### ISSUE THREAD

**Issue by lilliehaddock** [PNNL-PREMIS/SLA#10]
Hi @bpbond, 

I think I am still a little confused about the current state of the litter section in `SLA.Rmd`. What is the end goal with finding the average SLA for the "other" samples? 

This isn't really a coding task, but more of me asking you to please review this section when you get a chance and to either tell me/walk me through what still needs to be done. 

Thank you in advance!

**Comment by bpbond** [comment]
Hi @lilliehaddock - thanks for asking. Truly! Don't hesitate to speak up when something isn't clear.

We'd like to use our SLA (area/mass) to compute leaf area index of the forest, which is useful and interesting to know. We can do this by multiplying, _on a species-specific basis_, SLA by litterfall (mass) = area. In more detail:

Litter mass  | multiplied by SLA of | equals
----------- | ------------- | -------
Oak leaves | Oak | Oak LAI
Beech leaves | Beech | Beech LAI
Tulip leaves | Tulip | Tulip LAI
Other leaves | **???** | Other LAI

But we have a problem (the  ??? above): our categories of litter and SLA don't match up. In particular, we have an "Other" litter category--what SLA do we use for that? We need to compute an "Other" SLA, and that should be the `weighted.mean()` of the SLA of the other dominant species: maple, sweetgum, black gum I think we've said. And the weights should be their basal area (proportional to their biomass and canopy leaf area) in the stand.

So, 
1. Filter inventory for 'other' species
2. For each plot, compute the species weights as sum of DBH^2
3. For each plot, compute the 'Other SLA' as weighted mean
4. Compute LAI of oak, beech, tulip, and other for each plot

Does this help?
