### ISSUE TITLE
LAI Progress

### ISSUE THREAD

**Issue by lilliehaddock** [PNNL-PREMIS/SLA#11]
**What we did:** LAI computed on a trap basis as opposed to the entire plot. This allowed us to see variability between traps, ultimately giving us an idea of the error within the traps/species/plot. (?)

**Concern:** LAI numbers seem high. Is this a code error? 

**To Do:** 
- [x] Create histogram of litter data for each plot

**Comment by bpbond** [comment]
The closest analogue I see is Morgan Monroe State Forest, which has litterfall of 240 gC/m2/yr (so ~480 g/m2/yr, very close to our mean of 473) and LAI of 4-5. 

See e.g. https://www.sciencedirect.com/science/article/pii/S0168192314002305

**Comment by bpbond** [comment]
![litter](https://user-images.githubusercontent.com/1956468/68300273-6c7f3c80-006b-11ea-8146-04807fb69c25.png)

**Comment by bpbond** [comment]
Deciduous tree LMA averages 75 g/m2 = 133 cm2/g SLA, from the [Poorter et al. 2009 meta-analysis](http://dx.doi.org/10.1111/j.1469-8137.2009.02830.x).

Our values average 247 cm2/g, with extreme values over  twice that.

**Comment by bpbond** [comment]
Hi @lilliehaddock -

See notes above. Basically, the litterfall data are right in line with places like MMSF, but the SLA numbers are very high; this in turn is driving our very high LAI values. So, why?

1. The LI-3100C meter is giving high numbers. Is it calibrated correctly? Is it possibly reporting two-sided area? 
2. Our weights are too low. Is the balance calibrated? Let's do a test weight. Try re-weighing a few samples and compare?
3. Data entry - no. This is systematic.
4. The SLA calculation is wrong. 😕

**Comment by lilliehaddock** [comment]
Hi @bpbond, 

Thank you for going through all of this. I agree, both the area meter and balance should be checked (maybe tomorrow when we are already at SERC?). I feel slightly reassured to know that the litter data isn't out of the ordinary. 

I'll review the SLA calculation, though, to me, it seems very straightforward. (???)

**Comment by bpbond** [comment]
But SLA data seem very in line with TRY...see #13 .  😕

**Comment by bpbond** [comment]
Chris Gough notes:
>A couple of thoughts: Our site-wide weighted SLA is 190, which, if applied to your site would bring LAI down to 9.5, still high, but not at all impossible.

Let's definitely take a test weight to that SERC balance...

**Comment by lilliehaddock** [comment]
Are Chris's site data here? If so which is it? 
![image](https://user-images.githubusercontent.com/51174695/68428316-eaca0480-0179-11ea-888b-824cd51159f8.png)
