### ISSUE TITLE
2022-02-07

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/SLA#20]
- [x] Move this repo to `COMPASS-DOE`

Notes:
- ~We should look at SLA vs. DBH on a plot for all species combined~
- ~sun/shade should be included in models~
- DBH by site
- ~No sweetgum in the TRY database?~
- Check for papers we can site from PREMIS / COMPASS

To Do:
- [x] Pull salinity data (look @ what we used for the transplant paper)
- [x] Revise model 
- [ ] Choose which figures from the existing doc we should use
- [ ] Updated plots

**Comment by bpbond** [comment]
I just double-checked TRY and it seems correct that Sweetgum seems to have no data for SLA (trait ID 3116 or 3056). 😕
