### ISSUE TITLE
SLA Reading List

### ISSUE THREAD

**Issue by lilliehaddock** [PNNL-PREMIS/SLA#3]
### Paper examining some of the shortcomings of SLA:
- [x] https://nph.onlinelibrary.wiley.com/doi/pdf/10.1046/j.1469-8137.1999.00427.x

### A classic paper from Peter Reich, synthesizing data (including) SLA to understand plants growth strategies:
- [x]  https://link.springer.com/article/10.1007/s004420050471

### Interesting methods paper, looking at change over time:
- [x]  https://besjournals.onlinelibrary.wiley.com/doi/full/10.1046/j.0269-8463.2001.00563.x
---
### The important of open baseline data:
- [ ] https://onlinelibrary.wiley.com/doi/10.1111/gcb.14442
- [ ] http://dx.doi.org/10.1111/j.1365-2486.2012.02693.x

### Using SLA data to calculate canopy leaf area:
- [x] http://dx.doi.org/10.1093/treephys/22.14.993
- [ ] https://www.sciencedirect.com/science/article/pii/S0168192305000055

### Global importance of SLA and other traits vis-a-vis plant distribution and growth:
- [x] https://www.nature.com/articles/nature16489
- [ ] https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1111/1365-2745.12221
- [ ] https://onlinelibrary.wiley.com/doi/full/10.1111/j.1461-0248.2012.01852.x

### ...and community assembly:
- [ ] https://onlinelibrary.wiley.com/doi/full/10.1111/jvs.12041
- [ ] https://academic.oup.com/aob/article/108/7/1337/135123

### Importance of SLA and traits for global models:
- [x] http://dx.doi.org/10.1029/2011JG001913

**Comment by stephpenn1** [comment]
From SULI repo:

Remember, for most of these is _not_ to spend hours reading extremely closely, but rather to familiarize yourself with scientific issues and underlying science.
 
The important of open baseline data:
https://onlinelibrary.wiley.com/doi/10.1111/gcb.14442
http://dx.doi.org/10.1111/j.1365-2486.2012.02693.x

Using SLA data to calculate canopy leaf area:
http://dx.doi.org/10.1093/treephys/22.14.993
https://www.sciencedirect.com/science/article/pii/S0168192305000055

Global importance of SLA and other traits vis-a-vis plant distribution and growth:
https://www.nature.com/articles/nature16489
https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1111/1365-2745.12221
https://onlinelibrary.wiley.com/doi/full/10.1111/j.1461-0248.2012.01852.x

...and community assembly:
https://onlinelibrary.wiley.com/doi/full/10.1111/jvs.12041
https://academic.oup.com/aob/article/108/7/1337/135123

Importance of SLA and traits for global models:
http://dx.doi.org/10.1029/2011JG001913

**Comment by bpbond** [comment]
@stephpenn1 from an unpublished manuscript I'm editor on:

>In addition to climate, soil conditions strongly affect leaf morphology. For instance, an analysis of leaf data of 1,509 species worldwide has shown that specific leaf area (SLA) decreases with the increase of soil pH (Maire et al., 2015). Leaves of species growing in low nutrient soil are narrower than those in high nutrient soil (Cunningham et al., 1999), and SLA is positively correlated with mineral nutrients in the soil (Cunningham et al., 1999; Niinemets, 1999; Niinemets & Kull, 2003). Soil organic carbon affects leaf area of Embothrium coccineum (Souto et al., 2009). Leaf area of Ricinus communis increases after supplying plant residues to increase soil N, P, K, Ca, Mg and pH (Kano et al., 2004). In general, plants growing in the soil with low nutrients tend to have smaller leaves than those in fertile soils (Mcdonald et al., 2003).

This is from "2022 JGR Hou" — when useful, I can pull this for you.

**Comment by bpbond** [comment]
Parker, G. G. and Tibbs, D. J.: Structural Phenology of the Leaf Community in the Canopy of a Liriodendron tulipifera L. Forest in Maryland, USA, For. Sci., 50, 387, 2004.

**Comment by bpbond** [comment]
Just published: "Divergent response and adaptation of specific leaf area to environmental change at different spatio‐temporal scales jointly improve plant survival" https://onlinelibrary.wiley.com/doi/10.1111/gcb.16518

**Comment by bpbond** [comment]
Recent Chen and Kirwan Nature Geoscience paper https://www.nature.com/articles/s41561-022-01041-x

"These observations imply that SLR is driving the migration of coastal ecosystems over large spatial scales"

Also see second paragraph of paper.

**Comment by bpbond** [comment]
Just published

Leaf economics fundamentals explained by optimality principles
https://www.science.org/doi/10.1126/sciadv.add5667
