### ISSUE TITLE
SLA Manuscript Statistics Section

### ISSUE THREAD

**Issue by lilliehaddock** [PNNL-PREMIS/SLA#7]
We need to begin working on the statistics section of the SLA manuscript. **Exciting!**

@bpbond, could you create an outline in a new branch for what this could look like, including the different tests that need to be ran, and then schedule a meeting with me in the next few weeks to go over everything?

**Comment by bpbond** [comment]
>Our goals were to (i) characterize SLA across a broad range of species, elevations, and canopy heights in these forests; (ii) examine canopy structural differences in near-shore and upland trees; and (iii) infer how changes in future salinity might affect SLA, and thus canopy physiology, by comparing same-species SLA values along the creek's salinity gradient.

Before creating a branch, let's see. We're going to want to test:
1. _Differences between species_. This can be done once ignoring all other factors (`m <- lm(sla ~ species), aov(m)`) but then once with everything included (same as test in 4 below?)
2. _Differences between canopy height_. Dataset only for a few species. This is a paired t-test `t.test(sla_low, sla_heigh, paired = TRUE, var.equal = TRUE)` for each species
3. _Differences between early and late season_ . This is GCREW only and we can use a paired t-test `t.test(sla_early, sla_late, paired = TRUE, var.equal = TRUE)` for each species
4. _Shoreline versus upland_. This should nest elevation within site, using a mixed-effects model: `lmer(sla ~ elevation * species + (1 | site:elevation))`
5. _Salinity effect_. This codes GCREW as base level of contrast; no elevation or height factor. `lm(sla ~ site * species)`

**Comment by lilliehaddock** [comment]
Thanks, Ben! This is honestly really helpful for me to visualize what the stats section will look like/include.

**Comment by bpbond** [comment]
Good! Me too, actually.
