### ISSUE TITLE
October 28-Nov 1 To Do

### ISSUE THREAD

**Issue by lilliehaddock** [PNNL-PREMIS/SLA#8]
**For Tuesday meeting:** 
- [x] Names of 5 people to email for AGU meetings
- [x] Find bugs in inventory section of `SLA.Rmd`

**General:** 
- [x] Email Chris Gough to follow up about AGU registration/travel
- [x] Find bugs in salinity section of `SLA.Rmd`
- [x] Norbert Transplant Data
- [x] Aditi Subset Data
- [ ] Compare litter data with collected litter in 1207
- [x] Begin data analysis list #9 
- [ ] Manuscript Intro paragraph 2

**Comment by bpbond** [comment]
Sounds good! Specifically re "Find bugs", I think we said making sure that every single SLA tree is matched with exactly zero or one trees from the inventory data.

**Comment by stephpenn1** [comment]
- [ ] Email people about AGU meetings
- [x] Email Jess Shue for FG diameters on 4 missing trees
